# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drs_protocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64rs_protocol.proto\x12\x0c\x64rs_protocol\";\n\x07Request\x12\x0e\n\x06UserId\x18\x01 \x01(\r\x12\x12\n\nSessionKey\x18\x02 \x01(\t\x12\x0c\n\x04\x42ody\x18\x03 \x01(\t\")\n\x08Response\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\x0c\n\x04\x42ody\x18\x02 \x01(\t\"P\n\x16JobPollResponseMessage\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\x0c\n\x04\x42ody\x18\x02 \x01(\t\x12\x17\n\x0f\x46ragmentIndexes\x18\x03 \x03(\x05\x32\xf3\x02\n\x0bJobsManager\x12\x41\n\x0e\x43onnectRequest\x12\x15.drs_protocol.Request\x1a\x16.drs_protocol.Response\"\x00\x12@\n\rRenderRequest\x12\x15.drs_protocol.Request\x1a\x16.drs_protocol.Response\"\x00\x12O\n\x0eJobPollRequest\x12\x15.drs_protocol.Request\x1a$.drs_protocol.JobPollResponseMessage\"\x00\x12\x44\n\x11UpdateRoleRequest\x12\x15.drs_protocol.Request\x1a\x16.drs_protocol.Response\"\x00\x12H\n\x15ReportProgressRequest\x12\x15.drs_protocol.Request\x1a\x16.drs_protocol.Response\"\x00\x42\x0fZ\r/drs_protocolb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_JOBPOLLRESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['JobPollResponseMessage']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'drs_protocol_pb2'
  # @@protoc_insertion_point(class_scope:drs_protocol.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'drs_protocol_pb2'
  # @@protoc_insertion_point(class_scope:drs_protocol.Response)
  })
_sym_db.RegisterMessage(Response)

JobPollResponseMessage = _reflection.GeneratedProtocolMessageType('JobPollResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _JOBPOLLRESPONSEMESSAGE,
  '__module__' : 'drs_protocol_pb2'
  # @@protoc_insertion_point(class_scope:drs_protocol.JobPollResponseMessage)
  })
_sym_db.RegisterMessage(JobPollResponseMessage)

_JOBSMANAGER = DESCRIPTOR.services_by_name['JobsManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\r/drs_protocol'
  _REQUEST._serialized_start=36
  _REQUEST._serialized_end=95
  _RESPONSE._serialized_start=97
  _RESPONSE._serialized_end=138
  _JOBPOLLRESPONSEMESSAGE._serialized_start=140
  _JOBPOLLRESPONSEMESSAGE._serialized_end=220
  _JOBSMANAGER._serialized_start=223
  _JOBSMANAGER._serialized_end=594
# @@protoc_insertion_point(module_scope)
